### ISSUE TITLE
package version 2.3.0 release

### ISSUE THREAD

**Issue by Timple** [novatel-gbp/novatel_oem7_driver-release#1]
I noticed a new 2.3.0 release of the driver. Which holds some fixes.

Could this be bloomed (released) to the ROS buildfarm as well?

**Comment by novatel-applications-engineering** [comment]
3.0.0 release has been built, including previous changes.

**Comment by Timple** [comment]
Thank you!

But from what I can tell, the master branch is already on 3.0.1 for 21 days?
https://github.com/novatel/novatel_oem7_driver/commit/c7697f964b14618d0afbb456ef539a20a9d5f6c7

**Comment by novatel-applications-engineering** [comment]
That's a mistake we made on our end. 3.0.1 was a special that we built for a customer, and then we decided to check the changes into ROS1 and Master branch, proper labelling should be 3.0.0 for official release.

**Comment by novatel-applications-engineering** [comment]
version:
X.X.1 is special build for customer.
X.X.0 is official release.

**Comment by Timple** [comment]
But the package.xml still says 3.0.1.

So that certainly should align with the tag.

**Comment by novatel-applications-engineering** [comment]
Hi Timple, we are in the process of releasing 4.0.0 based on ROS1 branch (change merged to master), so this issue is addressed.
